/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Main settings": {                               "en": "Main settings",                                   "de": "Haupteinstellungen",                              "ru": "Основные параметры",                              "pt": "Configurações principais",                        "nl": "Belangrijkste instellingen",                      "fr": "Réglages principaux",                             "it": "Impostazioni principali",                         "es": "Ajustes principales",                             "pl": "Ustawienia główne",                               "zh-cn": "主要设置"},
    "readInterval": {                                "en": "read intervall [min]",                            "de": "Leseintervall [min]",                             "ru": "интервал чтения [мин]",                           "pt": "intervalo de leitura [min]",                      "nl": "lees interval [min]",                             "fr": "intervalle de lecture [min]",                     "it": "intervallo di lettura [min]",                     "es": "intervalo de lectura [min]",                      "pl": "interwał odczytu [min]",                          "zh-cn": "读取间隔 [分钟]"},
    "IsActive": {                                    "en": "active",                                          "de": "aktiv",                                           "ru": "активный",                                        "pt": "ativo",                                           "nl": "actief",                                          "fr": "actif",                                           "it": "attivo",                                          "es": "activo",                                          "pl": "aktywny",                                         "zh-cn": "积极的"},
    "name": {                                        "en": "name",                                            "de": "Name",                                            "ru": "имя",                                             "pt": "nome",                                            "nl": "naam",                                            "fr": "Nom",                                             "it": "nome",                                            "es": "nombre",                                          "pl": "Nazwa",                                           "zh-cn": "姓名"},
    "IPAddress": {                                   "en": "IP-Address",                                      "de": "IP Adresse",                                      "ru": "Айпи адрес",                                      "pt": "Endereço de IP",                                  "nl": "IP adres",                                        "fr": "Adresse IP",                                      "it": "Indirizzo IP",                                    "es": "Dirección IP",                                    "pl": "Adres IP",                                        "zh-cn": "IP地址"},
    "ApiKey": {                                      "en": "Api Key",                                         "de": "API-Schlüssel",                                   "ru": "API-ключ",                                        "pt": "Chave API",                                       "nl": "API sleutel",                                     "fr": "Clé API",                                         "it": "Chiave API",                                      "es": "Clave API",                                       "pl": "Klucz API",                                       "zh-cn": "API 密钥"},
    "Type": {                                        "en": "type",                                            "de": "Typ",                                             "ru": "тип",                                             "pt": "modelo",                                          "nl": "type",                                            "fr": "taper",                                           "it": "genere",                                          "es": "escribe",                                         "pl": "rodzaj",                                          "zh-cn": "类型"},
    "systems": {                                     "en": "systems",                                         "de": "Systeme",                                         "ru": "системы",                                         "pt": "sistemas",                                        "nl": "systemen",                                        "fr": "systèmes",                                        "it": "sistemi",                                         "es": "sistemas",                                        "pl": "systemy",                                         "zh-cn": "系统"},
};